'use strict'

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var FichaWarhammerSchema = Schema({
	jugadorid: { type: Schema.ObjectId, ref: "usuario" },
	jugador: String,
	nombre: String,
	raza: String,
	religion: String,
	profesionActual: String,
	profesionAnterior: String,
	avances: String,
	pxGanados: Number,
	descripcion: String,
	historia: String,
	Hai: Number,
	Hpi: Number,
	Fi: Number,
	Ri: Number,
	Agi: Number,
	Inti: Number,
	Vi: Number,
	Emi: Number,
	Hamejora: Number,
	Hpmejora: Number,
	Fmejora: Number,
	Rmejora: Number,
	Agmejora: Number,
	Intmejora: Number,
	Vmejora: Number,
	Emmejora: Number,
	Ha: Number,
	Hp: Number,
	F: Number,
	R: Number,
	Ag: Number,
	Int: Number,
	V: Number,
	Em: Number,
	Ai: Number,
	Hi: Number,
	Bfi: Number,
	Bri: Number,
	Mi: Number,
	Magi: Number,
	Pli: Number,
	Pdi: Number,	
	Amejora: Number,
	Hmejora: Number,
	Bfmejora: Number,
	Brmejora: Number,
	Mmejora: Number,
	Magmejora: Number,
	Plmejora: Number,
	Pdmejora: Number,	
	A: Number,
	H: Number,
	Bf: Number,
	Br: Number,
	M: Number,
	Mag: Number,
	Pl: Number,
	Pd: Number,	
	armasCc: String,
	armasP: String,
	movCombate: String,
	heridasRec: Number,
	puntosDestino: Number,
	cabeza: Number,
	bderecho: Number,
	bizquierdo: Number,
	cuerpo: Number,
	pderecha: Number,
	pizquierda: Number,
	armaduraAv: [],
	armaduraBasica: String,
	puntosLocalizacion: String,
	conocimientos: String,
	habilidadesBasicas: String,
	habilidadesSecundarias: String,
	talentos: String,
	carga: String,
	monedero: String,
	objetos: String, 
	avatar: String,
	juego: String,
	master: String,
	partida: String
});

module.exports = mongoose.model('FichaWarhammer', FichaWarhammerSchema);